/******************************************************************************/
/*                                                                            */
/* Debugging functions                                                        */
/*                                                                            */
/* Author: F. Wornle (FW-mn-yr)                                               */
/* Latest change: fw-07-08                                                    */
/*                                                                            */
/******************************************************************************/

/* data types */
#include "tmwtypes.h"


/* Model dependent constants -- generated by 'gen_mc_defines_h.m' */
#include "mc_defines.h"


// only include debug functions if required...
#if DEBUG_MSG_LVL > 0

#include "mc_debugMsgs.h"           /* DEBUG_DYNAMIC, DEBUG_MSG_LVL_MSGCOUNTER */
#include "bsp_sci.h"                /* SCI0_xxx function prototypes */



/* mangled debug messages? */
#if DEBUG_MSG_MNGL == 1


/* ----------------------------------------------------------------- */
/* using mangled debug messages                                      */
/* ----------------------------------------------------------------- */


/********************/
/* Global variables */
/********************/

/* default function name (debugging only)... this name is usually overridden locally  --  fw-07-07 */
#if DEBUG_MSG_LVL > 0
//const char_T *funcName = "Unknown Function";
const uint16_T funcName_ID = 0x907C;
#endif


/* dynamic debug level support */
#ifdef DEBUG_DYNAMIC
uint16_T    DynamicDbgMsgLvl = 0;          // 0: off, 1: level-1, 2: level-2, etc.
#endif


#ifdef DEBUG_MSG_LVL_MSGCOUNTER
// global message counter (debug)
uint16_T  msgCounter = 0;
#endif

/* define special escape characters */
#define DEBUG_XON    '^'                       // '^' must not be used in any debug message!
#define DEBUG_XOFF   '@'                       // '@' must not be used in any debug message!


/*===================*
 * Visible functions *
 *===================*/

//------------------------PRINT_DEBUG_MSG_ID1--------------------------
// general function to upload a single message ID
void funct_PRINT_DEBUG_MSG_ID1(const uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= DEBUG_MSG_LVL) {
        SCI0_OutChar(DEBUG_XON);
        SCI0_OutUHex( args );
        SCI0_OutChar(DEBUG_XOFF);
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutChar(DEBUG_XON);
    SCI0_OutUHex( args );
    SCI0_OutChar(DEBUG_XOFF);
    #endif  /* DEBUG_DYNAMIC */

}

//------------------------PRINT_DEBUG_MSG_ID2--------------------------
// general function to upload a function name and a message ID
void funct_PRINT_DEBUG_MSG_ID2(const uint16_T funcName_ID, const uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= DEBUG_MSG_LVL) {
        //SCI0_OutString( "[?] " );
        SCI0_OutChar(DEBUG_XON);
        SCI0_OutUHex( funcName_ID );
        SCI0_OutChar(DEBUG_XOFF);
        //SCI0_OutString( ": " );
        SCI0_OutChar(DEBUG_XON);
        SCI0_OutUHex( args );
        SCI0_OutChar(DEBUG_XOFF);
    }
    #else    /* DEBUG_DYNAMIC */
    //SCI0_OutString( "[?] " );
    SCI0_OutChar(DEBUG_XON);
    SCI0_OutUHex( funcName_ID );
    SCI0_OutChar(DEBUG_XOFF);
    //SCI0_OutString( ": " );
    SCI0_OutChar(DEBUG_XON);
    SCI0_OutUHex( args );
    SCI0_OutChar(DEBUG_XOFF);
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_UDec-----------------------
// general function to upload a decimal value
void funct_PRINT_DEBUG_MSG_UDec(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= DEBUG_MSG_LVL) {
        SCI0_OutUDec( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUDec( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_UHex-----------------------
// general function to upload a hexadecimal value
void funct_PRINT_DEBUG_MSG_UHex(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= DEBUG_MSG_LVL) {
        SCI0_OutUHex( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUHex( args );
    #endif  /* DEBUG_DYNAMIC */
    
}


//------------------------PRINT_DEBUG_MSG_LVL--------------------------
void funct_PRINT_DEBUG_MSG_LVL(const uint16_T funcName_ID, char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= DEBUG_MSG_LVL) {
        //SCI0_OutString( "[?] " );
        SCI0_OutChar(DEBUG_XON);
        SCI0_OutUHex( funcName_ID );
        SCI0_OutChar(DEBUG_XOFF);
        //SCI0_OutString( ": " );
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    //SCI0_OutString( "[?] " );
    SCI0_OutChar(DEBUG_XON);
    SCI0_OutUHex( funcName_ID );
    SCI0_OutChar(DEBUG_XOFF);
    //SCI0_OutString( ": " );
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */

}

//----------------------PRINT_DEBUG_MSG_LVL_Raw-----------------------
void funct_PRINT_DEBUG_MSG_LVL_Raw(char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= DEBUG_MSG_LVL) {
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */
    
}




#else


/* ----------------------------------------------------------------- */
/* not using mangled debug messages                                  */
/* ----------------------------------------------------------------- */


/********************/
/* Global variables */
/********************/

/* default function name (debugging only)... this name is usually overridden locally  --  fw-07-07 */
#if DEBUG_MSG_LVL > 0
const char_T *funct_name = "Unknown Function";
#endif


/* dynamic debug level support */
#ifdef DEBUG_DYNAMIC
uint16_T  DynamicDbgMsgLvl = 0;            // 0: off, 1: level-1, 2: level-2, etc.
#endif


#ifdef DEBUG_MSG_LVL_MSGCOUNTER
// global message counter (debug)
uint16_T  msgCounter = 0;
#endif



/*===================*
 * Visible functions *
 *===================*/


// DEBUG_MSG_LVL 1 ========================================================
#if DEBUG_MSG_LVL >= 1

//------------------------PRINT_DEBUG_MSG_LVL1--------------------------
void funct_PRINT_DEBUG_MSG_LVL1(const char_T *funct_name, const char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 1) {
        SCI0_OutString( "[1] " );
        SCI0_OutString( funct_name );
        SCI0_OutString( ": " );
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString( "[1] " );
    SCI0_OutString( funct_name );
    SCI0_OutString( ": " );
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL1_Raw-----------------------
void funct_PRINT_DEBUG_MSG_LVL1_Raw(const char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 1) {
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL1_UDec-----------------------
void funct_PRINT_DEBUG_MSG_LVL1_UDec(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 1) {
        SCI0_OutUDec( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUDec( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL1_UHex-----------------------
void funct_PRINT_DEBUG_MSG_LVL1_UHex(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 1) {
        SCI0_OutUHex( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUHex( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//-------------------------PRINT_DEBUG_MSG_NL1--------------------------
void funct_PRINT_DEBUG_MSG_NL1(void) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 1) {
        SCI0_OutString("\n\r");
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString("\n\r");
    #endif  /* DEBUG_DYNAMIC */
    
}


// DEBUG_MSG_LVL 2 ========================================================
#if DEBUG_MSG_LVL >= 2

//------------------------PRINT_DEBUG_MSG_LVL2--------------------------
void funct_PRINT_DEBUG_MSG_LVL2(const char_T *funct_name, const char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 2) {
        SCI0_OutString( "-[2] " );
        SCI0_OutString( funct_name );
        SCI0_OutString( ": " );
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString( "-[2] " );
    SCI0_OutString( funct_name );
    SCI0_OutString( ": " );
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL2_Raw-----------------------
void funct_PRINT_DEBUG_MSG_LVL2_Raw(const char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 2) {
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL2_UDec-----------------------
void funct_PRINT_DEBUG_MSG_LVL2_UDec(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 2) {
        SCI0_OutUDec( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUDec( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL2_UHex-----------------------
void funct_PRINT_DEBUG_MSG_LVL2_UHex(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 2) {
        SCI0_OutUHex( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUHex( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//-------------------------PRINT_DEBUG_MSG_NL2--------------------------
void funct_PRINT_DEBUG_MSG_NL2(void) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 2) {
        SCI0_OutString("\n\r");
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString("\n\r");
    #endif  /* DEBUG_DYNAMIC */
    
}


// DEBUG_MSG_LVL 3 ========================================================
#if DEBUG_MSG_LVL >= 3

//------------------------PRINT_DEBUG_MSG_LVL3--------------------------
void funct_PRINT_DEBUG_MSG_LVL3(const char_T *funct_name, const char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 3) {
        SCI0_OutString( "--[3] " );
        SCI0_OutString( funct_name );
        SCI0_OutString( ": " );
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString( "--[3] " );
    SCI0_OutString( funct_name );
    SCI0_OutString( ": " );
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL3_Raw-----------------------
void funct_PRINT_DEBUG_MSG_LVL3_Raw(const char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 3) {
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL3_UDec-----------------------
void funct_PRINT_DEBUG_MSG_LVL3_UDec(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 3) {
        SCI0_OutUDec( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUDec( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL3_UHex-----------------------
void funct_PRINT_DEBUG_MSG_LVL3_UHex(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 3) {
        SCI0_OutUHex( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUHex( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//-------------------------PRINT_DEBUG_MSG_NL3--------------------------
void funct_PRINT_DEBUG_MSG_NL3(void) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 3) {
        SCI0_OutString("\n\r");
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString("\n\r");
    #endif  /* DEBUG_DYNAMIC */
    
}


// DEBUG_MSG_LVL 4 ========================================================
#if DEBUG_MSG_LVL >= 4

//------------------------PRINT_DEBUG_MSG_LVL4--------------------------
void funct_PRINT_DEBUG_MSG_LVL4(const char_T *funct_name, const char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 4) {
        SCI0_OutString( "---[4] " );
        SCI0_OutString( funct_name );
        SCI0_OutString( ": " );
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString( "---[4] " );
    SCI0_OutString( funct_name );
    SCI0_OutString( ": " );
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL4_Raw-----------------------
void funct_PRINT_DEBUG_MSG_LVL4_Raw(const char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 4) {
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL4_UDec-----------------------
void funct_PRINT_DEBUG_MSG_LVL4_UDec(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 4) {
        SCI0_OutUDec( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUDec( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL4_UHex-----------------------
void funct_PRINT_DEBUG_MSG_LVL4_UHex(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 4) {
        SCI0_OutUHex( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUHex( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//-------------------------PRINT_DEBUG_MSG_NL4--------------------------
void funct_PRINT_DEBUG_MSG_NL4(void) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 4) {
        SCI0_OutString("\n\r");
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString("\n\r");
    #endif  /* DEBUG_DYNAMIC */
    
}


// DEBUG_MSG_LVL 5 ========================================================
#if DEBUG_MSG_LVL >= 5

//------------------------PRINT_DEBUG_MSG_LVL5--------------------------
void funct_PRINT_DEBUG_MSG_LVL5(const char_T *funct_name, const char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 5) {
        SCI0_OutString( "----[5] " );
        SCI0_OutString( funct_name );
        SCI0_OutString( ": " );
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString( "----[5] " );
    SCI0_OutString( funct_name );
    SCI0_OutString( ": " );
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL5_Raw-----------------------
void funct_PRINT_DEBUG_MSG_LVL5_Raw(const char_T *args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 5) {
        SCI0_OutString( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL5_UDec-----------------------
void funct_PRINT_DEBUG_MSG_LVL5_UDec(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 5) {
        SCI0_OutUDec( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUDec( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//----------------------PRINT_DEBUG_MSG_LVL5_UHex-----------------------
void funct_PRINT_DEBUG_MSG_LVL5_UHex(uint16_T args) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 5) {
        SCI0_OutUHex( args );
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutUHex( args );
    #endif  /* DEBUG_DYNAMIC */
    
}

//-------------------------PRINT_DEBUG_MSG_NL5--------------------------
void funct_PRINT_DEBUG_MSG_NL5(void) {

    #ifdef DEBUG_DYNAMIC
    if(DynamicDbgMsgLvl >= 5) {
        SCI0_OutString("\n\r");
    }
    #else    /* DEBUG_DYNAMIC */
    SCI0_OutString("\n\r");
    #endif  /* DEBUG_DYNAMIC */
    
}

#endif /* DEBUG_MSG_LVL 5 */
#endif /* DEBUG_MSG_LVL 4 */
#endif /* DEBUG_MSG_LVL 3 */
#endif /* DEBUG_MSG_LVL 2 */
#endif /* DEBUG_MSG_LVL 1 */


#endif /* DEBUG_MSG_MNGL */

#endif /* DEBUG_MSG_LVL */
