/*
 *********************************************************************************************************
 *
 * SCI support functions, application independent part (bord support package), Freescale MC9S12
 *                        adapted for rtmc9s12-target (reduced functionality, debug system, timeouts)
 *
 * (c) Frank Wörnle, 2010
 * 
 *********************************************************************************************************
 *
 * File              : bsp_sci.c
 * Version           : 1.00
 * Last modification : 11.04.2010, Frank Wörnle, adapted for rtmc9s12-target
 *
 *********************************************************************************************************
 */

 

/*
 *********************************************************************************************************
 *    INCLUDES
 *********************************************************************************************************
 */

#include "bsp_includes.h"                        /* all controller specific includes         */
#include "bsp_rBuf.h"                            /* (optional) ring buffer support           */
#include "bsp_sci.h"                             /* comms macros, application dependent fcts */
#include "bsp_rti.h"                             /* RTI support functions (timeout)          */
#include "bsp_err.h"                             /* error memory support                     */

/* Model dependent constants -- generated by 'gen_mc_defines_h.m' */
#include "mc_defines.h"



/*
 *********************************************************************************************************
 *    DEFINES
 *********************************************************************************************************
 */



/*
 *********************************************************************************************************
 *    CONSTANTS
 *********************************************************************************************************
 */



/*
 *********************************************************************************************************
 *    MODULE GLOBAL VARIABLES
 *********************************************************************************************************
 */

#if DEBUG_MSG_LVL > 0

    #define  maxDigit                               12                   /* max. value : +4294967295  ->  11 + 1 digits     */

    #if BSP_SCI0_SUPP == 1
    static tCHAR   outStr_SCI0[maxDigit];                                /* module global output buffer, SCI0               */
    #endif

#endif  /* DEBUG_MSG_LVL */



/*
 *********************************************************************************************************
 *    FUNCTION PROTOTYPES
 *********************************************************************************************************
 */



/*
 *********************************************************************************************************
 *    LOCAL FUNCTIONS
 *********************************************************************************************************
 */


#if DEBUG_MSG_LVL > 0

    /*
     *********************************************************************************************************
     * Function      : i_OutUxDec()
     *
     * Description   : local helper function called by SCIx_OutUyDec()
     * Arguments     : number to be transmitted (unsigned long), pointer to the last element of the output buffer
     * Return values : pointer to the beginning of the string to be transmitted
     *********************************************************************************************************
     */

    static tCHAR *i_OutUxDec(tINT32U num, tCHAR *buf) {

    tINT8U  nInBuf = 0;

        /* set 'end of string' marker */
        *buf = '\0';
        nInBuf++;
        
        /* next storage location -> one before current */
        buf--;

        /* assemble string, character by character */
        while (num >= 10 && nInBuf < maxDigit - 1) {
            
            /* store least significant digit at the end of the string */
            *buf = (tCHAR)('0' + num % 10);
            nInBuf++;
            
            /* next storage location */
            buf--;
            
            /* remove digit */
            num = num / 10;
            
        }
        
        /* store last remaining digit (= the most significant digit) */
        *buf = (tCHAR)('0' + num);
        
        /* return pointer to the beginning of the string to be transmitted */
        return buf;

    }



    /*
     *********************************************************************************************************
     * Function      : i_OutUxHex()
     *
     * Description   : local helper function called by SCIx_OutUyHex()
     * Arguments     : number to be transmitted (unsigned long), pointer to the last element of the output buffer
     * Return values : pointer to the beginning of the string to be transmitted
     *********************************************************************************************************
     */

    static tCHAR *i_OutUxHex(tINT32U num, tCHAR *buf) {

    tINT8U  currNibble;
    tINT8U  nInBuf = 0;

        /* set 'end of string' marker */
        *buf = '\0';
        nInBuf++;
        
        /* next storage location -> one before current */
        buf--;

        /* assemble string, character by character */
        while (num >= 16 && nInBuf < maxDigit - 1) {
            
            /* determine least significant nibble at the end of the string */
            currNibble = (tINT8U)(num % 16);
            
            if(currNibble >= 10) {
            
                /* A - F  ->  store hex digit */
                *buf = (tCHAR)('A' + currNibble % 10);
                
            } else {
              
                /* 0 - 9  ->  store dec digit */
                *buf = (tCHAR)('0' + currNibble);
                
            }
       
            /* increase character count */
            nInBuf++;
            
            /* next nibble */
            buf--;
            
            /* remove nibble */
            num = num >> 4;
            
        }
        
        /* store last remaining nibble (= the most significant nibble) */
        currNibble = (tINT8U)(num % 16);
            
        if(currNibble >= 10) {
            
            /* A - F  ->  store hex digit */
            *buf = (tCHAR)('A' + currNibble % 10);
                
        } else {
              
            /* 0 - 9  ->  store dec digit */
            *buf = (tCHAR)('0' + currNibble);
                
        }
        
        /* store prefix '0x'
         * note: the buffer cannot overflow because the max hex number is smaller than the max dec number
         */
        buf--;
        *buf = 'x';
        buf--;
        *buf = '0';
        
        /* return pointer to the beginning of the string to be transmitted */
        return buf;

    }

#endif  /* DEBUG_MSG_LVL */




/*
 *********************************************************************************************************
 *    PUBLIC FUNCTIONS
 *********************************************************************************************************
 */



/*
 *********************************************************************************************************
 *    Serial Communication Interface SCI0
 *********************************************************************************************************
 */

#if BSP_SCI0_SUPP == 1


#ifdef ERASE

/*
 *********************************************************************************************************
 * Function      : SCI0_InString()
 *
 * Description   : Read a string from SCI0. The function returns when specified maximum 
 *                 number of characters has been received or a timeout has occurred.
 * Arguments     : pointer to the string buffer
 *                 maximum number of characters to be received
 * Return values : EXT_ERROR / EXT_NO_ERROR
 * Comment       : function blocks until either of the above return conditions is true
 *********************************************************************************************************
 */

tBOOLEAN SCI0_InString(tINT8U *buf, tINT16U nBytesToGet) {

tINT16U  currLen = 0;
tINT16U  bTimeout;
tINT8U   currData;


    while (currLen < nBytesToGet) {
    
        /* fetch first character (blocks until character has arrived or timeout has occurred) */
        bTimeout = SCI0_InChar(&currData);
            
        /* timeout? */
        if (bTimeout == -1) {
            
            /* yes -> return EXT_ERROR */
            return EXT_ERROR;
            
        } else {

            /* regular character -> store character */
            *buf = currData;
            
            /* next storage location */
            buf++;
            currLen++; 
            
            /* echo character back to sender (terminal mode) */
            #ifdef BSP_SCI0_TERM_ECHO
            (tVOID)SCI0_OutChar(currData);
            #endif
            
        }
        
    }
    
    /* string read successfully -> return EXT_NO_ERROR */
    return EXT_NO_ERROR;

}

#endif  /* ERASE */


/*
 *********************************************************************************************************
 * Function      : SCI0_OutString()
 *
 * Description   : Transmit a string on SCI0. The string to be transmitted needs to be '\0' delimited.
 * Arguments     : pointer to the string to be transmitted
 * Return values : none
 *********************************************************************************************************
 */

tVOID SCI0_OutString(const tCHAR *buf) {

    /* transmit characters until the terminating '\0' is found */
    while (*buf) {
    
        /* transmit next character */
        (tVOID)SCI0_OutChar((tINT8U)*buf);
        
        /* advance pointer by one character */
        buf++;
      
    }
    
}



#if DEBUG_MSG_LVL > 0

    /*
     *********************************************************************************************************
     * Function      : SCI0_OutUDec()
     *
     * Description   : Transmit an unsigned decimal number via SCI0
     * Arguments     : unsigned short  --  the number to be transmitted
     * Return values : none
     *********************************************************************************************************
     */

    tVOID SCI0_OutUDec(tINT16U num) {

    tCHAR   *strPtr = &outStr_SCI0[maxDigit];

        /* assemble string to be transmitted (call to local function) */
        strPtr = i_OutUxDec((tINT32U)num, strPtr);
        
        /* transmit string */
        SCI0_OutString(strPtr);

    }



    /*
     *********************************************************************************************************
     * Function      : SCI0_OutUHex()
     *
     * Description   : Transmit an unsigned hexadecimal number via SCI0
     * Arguments     : unsigned short  --  the number to be transmitted
     * Return values : none
     *********************************************************************************************************
     */

    tVOID SCI0_OutUHex(tINT16U num) {

    tCHAR   *strPtr = &outStr_SCI0[maxDigit];

        /* assemble string to be transmitted (call to local function) */
        strPtr = i_OutUxHex((tINT32U)num, strPtr);
        
        /* transmit string */
        SCI0_OutString(strPtr);

    }

#endif  /* DEBUG_MSG_LVL */


#endif /* BSP_SCI0_SUPP */





/*
 *********************************************************************************************************
 *    Serial Communication Interface SCI1
 *********************************************************************************************************
 */

#if BSP_SCI1_SUPP == 1


#ifdef ERASE

/*
 *********************************************************************************************************
 * Function      : SCI1_InString()
 *
 * Description   : Read a string from SCI1. The function returns when the specified maximum 
 *                 number of characters has been received or a timeout has occurred.
 * Arguments     : pointer to the string buffer
 *                 maximum number of characters to be received
 * Return values : EXT_ERROR / EXT_NO_ERROR
 * Comment       : function blocks until either of the above return conditions is true
 *********************************************************************************************************
 */

tBOOLEAN SCI1_InString(tINT8U *buf, tINT16U nBytesToGet) {

tINT16U  currLen = 0;
tINT16U  bTimeout;
tINT8U   currData;


    while (currLen < nBytesToGet) {
    
        /* fetch first character (blocks until character has arrived or timeout has occurred) */
        bTimeout = SCI1_InChar(&currData);
            
        /* timeout? */
        if (bTimeout == -1) {
            
            /* yes -> return EXT_ERROR */
            return EXT_ERROR;
            
        } else {

            /* regular character -> store character */
            *buf = currData;
            
            /* next storage location */
            buf++;
            currLen++; 
            
            /* echo character back to sender (terminal mode) */
            #ifdef BSP_SCI1_TERM_ECHO
            (tVOID)SCI1_OutChar(currData);
            #endif
            
        }
        
    }
    
    /* string read successfully -> return EXT_NO_ERROR */
    return EXT_NO_ERROR;

}

#endif  /* ERASE */

/*
 *********************************************************************************************************
 * Function      : SCI1_OutString()
 *
 * Description   : Transmit a string on SCI1. The string to be transmitted needs to be '\0' delimited.
 * Arguments     : pointer to the string to be transmitted
 * Return values : none
 *********************************************************************************************************
 */

tVOID SCI1_OutString(const tCHAR *buf) {

    /* transmit characters until the terminating '\0' is found */
    while (*buf) {
    
        /* transmit next character */
        (tVOID)SCI1_OutChar((tINT8U)*buf);
        
        /* advance pointer by one character */
        buf++;
      
    }
    
}


#endif /* BSP_SCI1_SUPP */